### ISSUE TITLE
Better light theme support

### ISSUE THREAD

**Issue by remixer-dec** [internationalTD/defuser#11]
Some parts are unreadable with the light theme, editing css and adding more classes to already existing code fixes it: 
```css
@media (prefers-color-scheme: light), (prefers-color-scheme: lightest) {
/* ... */
 .group > sp-label:not(.safe), .group > label:not(.safe), .toaster, .group > sp-button {
    background-color: #E8E8E8;
  }
}
```

Also in your [preview](https://github.com/internationalTD/defuser/blob/main/docs/splash2.png) file all UI elements look pretty evenly spaced, but in my case they are [not like that
](https://i.imgur.com/vO0VWy5.png)
